# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog NewtriLabs
email: contacto@quetru.cl
description: >
  Últimas novedades de Newtri Labs. Actualizaremos esta página para anunciar nuevos lanzamientos y mostrar datos interesantes de nuestros proyectos en desarrollo.
logo: "/assets/images/logo.jpg"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.newtri.cl" # the base hostname & protocol for your site
paginate:	15 # The number of posts to show per page on your homepage

name: 'Newtri Labs'
bio: >
  Somos profesionales de la salud.
  Desarrollamos las aplicaciones que nos gustaría tener disponibles.
author_image: "/assets/images/autor.png"
# twitter_username: jekyllrb
github_username:  newtri

# Google Analytics
analytics_id: "UA-60759619-2"

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
